+ TypeScript typings
dzek69/react-source-of-truth pull request #5
Opened 2020-05-19 17:29 UTC by jurijtokarski

Added some basic typings for the library. I've tested it in some internal project, but I think we need to check it in some real-world project.

2020-05-19 17:30 UTC, jurijtokarski commented
CC @dzek69 :)

2020-05-19 20:43 UTC, dzek69 commented on tutorials/WithTypescript.md
> +# [Basic usage](https://github.com/jurijtokarski/react-source-of-truth/blob/master/tutorials/Usage.md) with TypeScript
replace this link with https://dzek69.github.io/react-source-of-truth/tutorial-Usage.html ;)

2020-05-19 20:53 UTC, dzek69 requested changes

2020-05-19 20:53 UTC, dzek69 commented on tutorials/WithTypescript.md
> +```
please add example with getState :) seems like this got cut off

2020-05-20 12:29 UTC, dzek69 approved these changes

2020-05-20 12:34 UTC, merged